apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-architeture-nestjs-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-architeture-nestjs-boilerplate
  template:
    metadata:
      labels:
        app: clean-architeture-nestjs-boilerplate
    spec:
      containers:
        - name: clean-architeture-nestjs-boilerplate
          image: image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
